---
id: change-license
base_name: change-license
tags:
- licensing
presentation_date: 2017/12/17
version: 2017.12.17
licenses: []
slideshare_id: ss-84299220
speaker_deck_id: raisensubian-geng-falsehua
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
